# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 4.13.0'

target 'ZaloApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZaloApp


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'ZaloAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ZaloApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZaloApp-tvOS

  target 'ZaloApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
